spring:
  application:
    name: observability-models-mistral-ai
  ai:
    chat:
      observations:
        include-completion: true
        include-prompt: true
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
      chat:
        options:
          model: mistral-small-latest
          temperature: 0.7
      embedding:
        options:
          model: mistral-embed

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
