spring:
  application:
    name: observability-models-ollama
  ai:
    chat:
      observations:
        include-completion: true
        include-prompt: true
    image:
      observations:
        include-prompt: true
    ollama:
      chat:
        options:
          model: mistral
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
