spring:
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          include: false
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw

arconia:
  dev:
    services:
      postgresql:
        image-name: pgvector/pgvector:pg17
