spring:
  application:
    name: observability-vector-stores-pgvector
  ai:
    chat:
      client:
        observations:
          include-input: true
      observations:
        include-completion: true
        include-prompt: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      observations:
        include-query-response: true
      pgvector:
        initialize-schema: true
        dimensions: 1536
        index-type: hnsw

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

arconia:
  dev:
    services:
      postgresql:
        image-name: pgvector/pgvector:pg17
