spring:
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: granite3.3:2b
      embedding:
        options:
          model: granite-embedding:30m
