spring:
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        embedding:
          include: false
      chat:
        options:
          model: llava-phi3
          temperature: 0.7
